### ISSUE TITLE
Cloudflare Workers

### ISSUE THREAD

**Issue by JBX2060** [cameronapak/freedom-stack#12]
Would be amazing if we can deploy it to Cloudflare Edge. Then we can take advantage of Astro's lightning speed and Turso.

**Comment by cameronapak** [comment]
Hey! Have you tried https://docs.astro.build/en/guides/integrations-guide/cloudflare/ to see what works and what doesn't, @JBX2060?

**Comment by cameronapak** [comment]
Closing this, but please let me know if it should be re-opened.
