### ISSUE TITLE
Choose a cheaper, in-house auth solution

### ISSUE THREAD

**Issue by cameronapak** [cameronapak/freedom-stack#13]
Clerk is great. 
LogTo is great.
They cost money.

I just heard about [Better Auth](https://www.better-auth.com/). How hard is that to implement?

**Comment by cameronapak** [comment]
https://logto.io/compare/clerk

**Comment by cameronapak** [comment]
Here's how to install https://www.better-auth.com/docs/installation

**Comment by cameronapak** [comment]
And, here's how to integrate: https://www.better-auth.com/docs/integrations/astro

**Comment by Lftobs** [comment]
> And, here's how to integrate: https://www.better-auth.com/docs/integrations/astro

This looks good

**Comment by cameronapak** [comment]
@Lftobs here's a close PR https://github.com/cameronapak/freedom-stack/pull/22

**Comment by Lftobs** [comment]
> @Lftobs thanks! I tried to implement it on a local branch, but it was harder than just a 1 hour go at it. Wanna give it a go?

Sure when I'm free I'll check it out

**Comment by cameronapak** [comment]
Thanks @Lftobs I was able to get it working and merged into main. Please try and let me know if it works well for you
