### ISSUE TITLE
No delete func on the site

### ISSUE THREAD

**Issue by Lftobs** [cameronapak/freedom-stack#17]
i kinda of created a blog post but can't find where to delete it on the site....would love to make a pr to fix tthis

**Comment by cameronapak** [comment]
@Lftobs please do!

**Comment by Lftobs** [comment]
> @Lftobs please do!

i don't have write access ... you will have to invite me to the repo

**Comment by cameronapak** [comment]
@Lftobs you did a great job. Thank you for contributing!

**Comment by cameronapak** [comment]
@Lftobs, you are now listed as a contributor on this project. However, when I look up the contributors via [contrib.rocks](https://contrib.rocks/image?repo=cameronapak/freedom-stack&anon=1), I only see myself. My thinking is that it's due to your name being `rm -rf` haha
