### ISSUE TITLE
Incorrect Links in the NPMjs listing

### ISSUE THREAD

**Issue by Dmjhop** [cameronapak/freedom-stack#46]
Hey FreedomStack Team/Cameron! 

I was just about to start a project using the Freedom Stack when I noticed on the npm lisiting that your Repository and Homepage links were incorrect. 

Right now they are listed as https://github.com/cameronpak/freedom-stack 

I think the only reason the links aren't working is because your middle initial "a" isn't in the original link

The correct link should be https://github.com/cameronapak/freedom-stack

Thanks for all you do!

Best,
David Hopkins II

**Comment by Dmjhop** [comment]
Oh let me not forget, Merry Christmas & Happy New Year to ya!

**Comment by cameronapak** [comment]
Aww, thanks! Merry Christmas @Dmjhop !

Thanks for pointing this out! I've made a fix in v1.0.8 :)
